version: '3.8'

services:
  app:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    command: expo start --tunnel # Override the command within Dockerfile. Only tunnel with phone seems to be working here. Having issues with networks/localhost/emulators
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      #- REACT_NATIVE_PACKAGER_HOSTNAME=10.0.0.2 --> Attempt to be able to work with Android emulator directly to no avail
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    volumes:
      - ./client:/usr/src/app

  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    command: npm run dev # Override the command within Dockerfile
    ports: 
      - 3001:3001
    volumes:
      - ./server:/usr/src/app
    environment:
      - PORT=3001
      - MONGODB_URI=<<VALID_ONE_GOES_HERE>>

  nginx:
    container_name: reverse-proxy
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app

  debug-helper:    
    image: busybox