version: '3.8'

services:
  app:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    command: expo start --tunnel # Override the command within Dockerfile. Only tunnel with phone seems to be working here. Having issues with networks/localhost/emulators
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    volumes:
      - ./client:/usr/src/app
    env_file:
      - ./client/.env

  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    command: npm run dev # Override the command within Dockerfile
    ports: 
      - 3001:3001
    volumes:
      - ./server:/usr/src/app
    env_file:
      - ./server/.env

  nginx:
    container_name: reverse-proxy
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app

  debug-helper:    
    image: busybox